### ISSUE TITLE
再次失效了

### ISSUE THREAD

**Issue by zhouwei-jazz** [xioneko/yanhekt-downloader#3]
前几天更新后能下载了，但今天又提示下载失败

**Comment by zhouwei-jazz** [comment]
![image](https://github.com/user-attachments/assets/33df56fb-d2be-48dd-bca2-7677640047a8)

**Comment by xioneko** [comment]
好像是签名算法更新了，今晚更新修复版本

**Comment by zhouwei-jazz** [comment]
收到
